[package]
name = "aprsserver"
version = "0.1.0"
edition = "2024"

[dependencies]
seahash = "4.1"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
